routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');

    return 'Commands run successfully Cleared.';
});
Route::get('/', function () {
    $investorCount = \App\User::where('user_type', 'investor')->count();
    $startupCount = \App\User::where('user_type', 'startup')->count();
    return view('welcome', compact('investorCount', 'startupCount'));

})->name('index');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

use App\Http\Controllers\StripeController;
use App\Http\Middleware\CheckPayment;

Route::middleware([CheckPayment::class])->group(function () {
    Route::get('investor', 'InvestorController@index')->name('investor.index');
    Route::get('/edit/investor/{id}', 'InvestorController@edit')->name('investor.edit');
    Route::post('/edit/investor/update', 'InvestorController@update')->name('investor.update');

    Route::get('/investor-message-inbox/{id}', 'InvestorController@viewMessage')->name('page.index');
    Route::get('/message', 'InvestorController@getMessage')->name('get-messages');
    Route::post('message', 'InvestorController@sendMessage')->name('store-messages');
    Route::get('/investor-message-all', 'InvestorController@getAllMessage')->name('investor-message-all.index');

    Route::get('startup', 'StartUpController@index')->name('startup.index');
    Route::get('/startup/create', 'StartUpController@create')->name('startup.create');
    Route::post('/startup/store', 'StartUpController@store')->name('startup.store');

    Route::get('/startup/profile/{id}', 'StartUpController@editProfile')->name('startup.profile');
    Route::post('/startup/profile/update', 'StartUpController@updateProfile')->name('startup.profile.update');


    Route::get('/discover', 'StartUpController@discover')->name('discover');
    Route::get('/startup/detail/{id}', 'StartUpController@startupDetail')->name('startup.detail');


    Route::get('/startup/edit/{id}', 'StartUpController@edit')->name('startup.edit');
    Route::post('/startup/update', 'StartUpController@update')->name('startup.update');
    Route::get('/startup/delete/{id}', 'StartUpController@destroy')->name('startup.delete');


//Route::get('/startup-message-all/{id}', 'StartUpController@viewMessage')->name('startup-get.index');
    Route::get('/startup-message-all', 'StartUpController@viewMessage')->name('startup-get.index');

    Route::get('/startup-message-get', 'StartUpController@getMessage')->name('startup-get-messages');
    Route::post('startup--store-message-guide', 'StartUpController@sendMessage')->name('startup-store-messages');
    Route::get('cancel/subscription', 'StartUpController@cancelSubscription')->name('cancel.subscription');

});


Route::get('payment', [StripeController::class, 'stripe'])->name('payment.index');
Route::post('payment/store', [StripeController::class, 'stripePost'])->name('payment.post');

Route::get('forget-password', 'AccountController@getEmail');
Route::post('forget-password', 'AccountController@postEmail');
Route::get('reset-password/{token}', 'AccountController@getPassword');
Route::post('reset-password', 'AccountController@updatePassword');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/investors', 'Backend\InvestorController');
        Route::resource('/startups', 'Backend\StartUpController');
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
    });
});
Route::resource('/contacts', 'Backend\ContactUsController', [
    'only' => ['create', 'store']
]);

//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('delete/startup/image', 'Backend\AjaxController@deleteStartupImage')->name('update.remove.image');
    Route::get('delete/startup/video', 'Backend\AjaxController@deleteStartupVideo')->name('update.remove.video');
});

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\StartupGallery;
use App\StartupVideo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;

class AjaxController extends Controller
{

    public function deleteStartupImage(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'remove_id' => 'required|exists:startup_galleries,id'
        ], [
            'remove_id.required' => "Image Id is Required.",
            'remove_id.exists' => "Invalid Image Id Selected."
        ]);

        if (!$validator->fails()) {
            StartupGallery::where('id', $request->get('remove_id'))->delete();
            $response['status'] = 'success';
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;

    }


    public function deleteStartupVideo(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'remove_id' => 'required|exists:startup_videos,id'
        ], [
            'remove_id.required' => "Video Id is Required.",
            'remove_id.exists' => "Invalid Image Id Selected."
        ]);

        if (!$validator->fails()) {
            StartupVideo::where('id', $request->get('remove_id'))->delete();
            $response['status'] = 'success';
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;

    }


}

app/Http/Controllers/Backend/ContactUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Mail\ContactUsEmail;
use App\ContactUs;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class ContactUsController extends Controller
{
    public function index()
    {
        $contacts = ContactUs::orderBy('id', 'DESC')->get();
        return view('backend.contacts.index', compact('contacts'));

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required',
            'description' => 'required'
        ]);
        $contact = ContactUs::create($request->all());
        $contact_us_email = Mail::to('info@mimofinds.ch')->send(new ContactUsEmail($contact));

        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'Your message has been sent.'
        ]);
    }

    public function destroy($id)
    {
        $contactus = ContactUs::findOrFail($id);
        $contactus->delete();

        return redirect()->route('admin.contacts.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Contact has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\User;

class DashboardController extends Controller
{
    public function __construct()
    {
    }

    public function index()
    {
        $investor_count = User::where('user_type', 'investor')->get()->count();
        $startup_count = User::where('user_type', 'startup')->get()->count();
        return view('backend.dashboard.index', compact('investor_count', 'startup_count'));
    }
}

app/Http/Controllers/Backend/InvestorController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Message;
use App\User;

class InvestorController extends Controller
{
    public function __construct()
    {
    }

    public function index()
    {
        $users = User::orderBy('id', 'DESC')->where('user_type', 'investor')->get();
        return view('backend.investors.index', compact('users'));
    }


    public function destroy($id)
    {
        $user = User::findOrFail($id);
        Message::where('from', $id)->delete();
        Message::where('to', $id)->delete();
        $user->delete();

        return redirect()->route('admin.investors.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Investor has been Deleted.'
            ]);
    }

}

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function __construct()
    {

    }

    public function index()
    {
        $setting = Setting::first();
        return view('backend.settings.index', compact('setting'));
    }


    public function update(Request $request, $id)
    {
        $setting =Setting::find($id);

        $setting->update([
            'payment_method' => $request->payment_method,
            'default_price' => $request->default_price,
            'current_price' => $request->current_price,
            'start_date' => $request->start_date,
            'end_date' => $request->end_date,
        ]);
        return redirect()->route('admin.settings.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Setting updated successfully.'
            ]);

    }
}

app/Http/Controllers/Backend/StartUpController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Message;
use App\Startup;
use App\StartupGallery;
use App\StartupVideo;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class StartUpController extends Controller
{
    public function __construct()
    {
    }

    public function index()
    {
        $users = User::orderBy('id', 'DESC')->where('user_type', 'startup')->get();
        return view('backend.startups.index', compact('users'));
    }


    public function destroy($id)
    {
        $user = User::findOrFail($id);
        Startup::where('user_id', $id)->delete();
        StartupVideo::where('startup_id', $id)->delete();
        StartupGallery::where('startup_id', $id)->delete();
        Message::where('from', $id)->delete();
        Message::where('to', $id)->delete();
        $user->delete();

        return redirect()->route('admin.startups.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Investor has been Deleted.'
            ]);
    }

}

resources/views/backend/investors/index.blade.php
@extends('layouts.master')
@section('title','Investors')
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Investors
                        </h3>
                    </div>
                </div>

            </div>

            <div class="m-portlet__body">
                <div class="responsiveTable">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                        <thead>
                        <tr>

                            <th> Sr No</th>
                            <th> Full Name</th>
                            <th> Email</th>
                            <th> Mobile Number</th>
                            <th> Gender</th>
                            <th> Role</th>
                            <th> Status</th>
                            <th> Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(!empty($users))
                            @foreach($users as $user)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{ucfirst($user->fullname())}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->phone_number}}</td>
                                    <td>{{$user->gender}}</td>
                                    <td>{{ucfirst($user->user_type)}}</td>
                                    <td style="width: 10%;">{{ucfirst($user->status)}}</td>
                                    <td class="d-flex">
                                        <form method="post"
                                              action="{{ route('admin.investors.destroy', $user->id) }}"
                                              id="delete_{{ $user->id }}">
                                            @csrf
                                            @method('DELETE')
                                            <a class="btn btn-sm btn-danger m-left"
                                               href="javascript:void(0)"
                                               onclick="if(confirmDelete()){ document.getElementById('delete_<?=$user->id?>').submit(); }">
                                                Delete
                                            </a>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        $("#m_table_1").dataTable({
            "ordering": false,
            "order": [[0, "desc"]],
            "columnDefs": [
                {orderable: false, targets: [7]}
            ],
        });


    </script>
@endpush